format = """
$directory\
$git_branch\
$git_status\
$fill\
$kubernetes\
$golang\
$docker_context\
$cmd_duration\
$line_break\
$character"""

add_newline = true 

palette = "dayfox"

# Starship modules
[character]
success_symbol = "[[󰇄](bold teal) ❯](pink)"
error_symbol = "[[󰇄](bold red) ❯](lavender)"
vimcmd_symbol = "[ ❮](subtext1)" # For use with zsh-vi-mode

[git_branch]
style = "bold mauve"

[directory]
style = "bold lavender"
format = '[$path ]($style)'
truncation_length = 3
truncation_symbol = '…/'
truncate_to_repo = false

[directory.substitutions]
'Documents' = '󰈙'
'Downloads' = ' '
'Music' = ' '
'Pictures' = ' '

[os]
disabled = false
style = "bg:color_orange fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Raspbian = "󰐿"
Macos = "󰀵"
Linux = "󰌽"
Arch = "󰣇"

[fill]
symbol = ' '

[docker_context]
symbol = ' '
style = 'fg:#06969A'
format = '[$symbol]($style) $path'
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
detect_extensions = ['Dockerfile']

[jobs]
symbol = ' '
style = 'red'
number_threshold = 1
format = '[$symbol]($style)'

[cmd_duration]
min_time = 500
style = 'fg:gray'
format = '[$duration]($style)'

[palettes.gruvbox_light]
red     = "#cc241d"
green   = "#98971a"
yellow  = "#d79921"
blue    = "#458588"
purple  = "#b16286"
teal    = "#689d6a"
orange  = "#d65d0e"
subtext = "#7c6f64"

[palettes.dayfox]
red     = "#e26d5c"
green   = "#6dae83"
yellow  = "#d19a66"
blue    = "#6099c0"
purple  = "#957fb8"
teal    = "#5aafb0"
orange  = "#d4956a"
subtext = "#a8adb7"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[golang]
style = 'sky'
symbol = ' '

[kubernetes]
disabled = false
symbol = "☸ "
format = '[$symbol$context( \($namespace\))]($style) '
style = "yellow bold"

